run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - gomoddirectives
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - gofumpt

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck

    #
    # Disabled because too strict:
    #
    - goerr113
    - prealloc

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  cyclop:
    max-complexity: 15

output:
  print-issued-lines: true
  sort-results: true
