name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        timeout-minutes: 10

      - name: Ensure go mod tidy runs without changes
        run: make mod
        timeout-minutes: 10

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: make test
        timeout-minutes: 10
